config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "user/index" => "user#index"
  get "photo/index/:id" => "photo#index", as: "user_photos"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
    @user = User.find_by(id: params[:id])
    @photos = Photo.where(user_id: params[:id])
    @comments = Comment.all
    @user_all = User.all
  end
  def display_name(user_id)
    @user = User.find_by(id: user_id)
    return @user.first_name
  end
  helper_method :display_name
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photosite2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photo/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>PhotoSite</title>
  <style>
    head{
      align-items: center;
    }
    h1{
      background-color: antiquewhite;
      padding-left: 38%;
      padding-right: 35%;
    }
    h3{
      background-color: lemonchiffon;
      padding-left: 44%;
      padding-right: 35%;
    }
    h2{
      background-color: azure;
      padding-left: 41%;
      padding-right: 35%;
    }
      img{
        margin-left: auto;
        margin-right: auto;
        display: block;

      }
      center{
        font-family: "Felix Titling";
        color: darkgreen;
      }
  </style>
</head>
<body>
<div>
  <h1 style="font-family: 'Bookman Old Style'; color: crimson">PhotoSite User List</h1>  <h3 style="font-family: 'Bell MT';">User Photo Page</h3>
</div>

  <h2>Photos of <%= link_to @user.first_name %> <%= link_to @user.last_name %></h2>
  <% @photos.each do |photo| %>
    <%= image_tag("/assets/#{photo.file_name}") %>
    <center> Photo created at   <%= photo.date_time %></center>

    <% @comments.where("photo_id=?",photo.id).each do |comment| %>

      <center> Comment: <%= comment.comment_text %></center>
      <center> Created at: <%= comment.date_time %></center>
      <center> Posted by: <%= link_to display_name(comment.user_id) , user_photos_path(comment.user_id) %></center>

    <% end %>
  <br>
  <br>
    </div>
  <%end%>
  </body>
</html>

app/views/user/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>PhotoSite</title>
  <style>
    h1{
      background-color: antiquewhite;
      padding-left: 38%;
      padding-right: 35%;
    }
    table{
      background-color: azure;
      border: 1px solid black;
      border-color: cadetblue;
      border-bottom-left-radius: 30px;
      border-bottom-right-radius: 30px;
      border-width: thick;
      border-collapse: collapse;
      width: 100%;
      height: auto;
    }
    th, td {
      border: 1px solid black;
      border-color: cadetblue;
      border-bottom-left-radius: 30px;
      border-bottom-right-radius: 30px;
      border-width: thick;
      border-collapse: collapse;
      padding: 10px;
    }
  </style>
</head>
<body>
<h1 style="font-family: 'Bookman Old Style'; color: crimson">PhotoSite User List</h1>

<table style="border-color: cadetblue; border-bottom-left-radius: 30px; border-bottom-right-radius: 30px; border-width: thick;">
  <thead >
  <th style="font-family: Perpetua;color: midnightblue; font-size: 30px;">User</th>
  <th style="font-family: Perpetua;color: midnightblue; font-size: 30px;">First</th>
  <th style="font-family: Perpetua;color: midnightblue; font-size: 30px;">Last</th>
  </thead>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.id, user_photos_path(user.id) %></td>
      <td><%= link_to user.first_name, user_photos_path(user.id) %></td>
      <td><%= link_to user.last_name, user_photos_path(user.id) %></td>
    </tr>
  <% end %>
</table>
</body>
</html>